server:
  port: 8090
spring:
  application:
    name: discodeit
  datasource:
    url: jdbc:h2:mem:discodeit_dev
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  boot:
    admin:
      client:
        url: http://localhost:9090
logging:
  level:
    root: debug
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
info:
  datasource:
    url: ${spring.datasource.url}
    driver-class-name: ${spring.datasource.driver-class-name}
    jpa:
      ddl-auto: ${spring.jpa.hibernate.ddl-auto}

discodeit:
  storage:
    type: local