server:
  port: 8090
spring:
  application:
    name: discodeit
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  boot:
#    admin:
#      client:
#        url: ${SPRING_BOOT_ADMIN_CLIENT_URL}
logging:
  level:
    root: info
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: info
    com.example.jwt: WARN
info:
  datasource:
  url: ${spring.datasource.url}
  driver-class-name: ${spring.datasource.driver-class-name}
  jpa:
    ddl-auto: ${spring.jpa.hibernate.ddl-auto}

management:
  info:
    env:
      enabled: false

jwt:
  secret: ${JWT_SECRET}  # 환경변수에서 주입 (필수)

